# -*- coding: utf-8 -*-
"""Red Wine Quality.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oyJwhIuHeT31soj5q2_vpC_b_yE19pTj

# Library Import
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme(color_codes=True)

"""# Data load"""

df = pd.read_csv('/content/sample_data/winequality-red.csv')

df.head()

df.tail()



"""# Data Processing Part-01"""

df.select_dtypes(include='object').nunique()

df.info()